name: funhub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
 sdk: ^3.5.2

dependencies:
 flutter:
   sdk: flutter
 google_fonts: ^4.0.0
 cupertino_icons: ^1.0.8
 connectivity_plus:
 firebase_database: ^11.1.4
 firebase_core: ^3.6.0
 app_tracking_transparency: ^2.0.6
 flutter_inappwebview:
 flutter_asa_attribution: ^1.0.0 
 onesignal_flutter: ^5.1.2
 in_app_review: ^2.0.9
 appsflyer_sdk: ^6.15.1
 shared_preferences: ^2.2.2
 url_launcher: ^6.2.4

dev_dependencies:
 flutter_test:
   sdk: flutter
 flutter_lints: ^4.0.0

flutter:
 uses-material-design: true
 assets:
   - assets/images/
   - assets/games/
   - assets/drinks/